### ISSUE TITLE
how to use this package for ground rover?

### ISSUE THREAD

**Issue by ahar** [PixelBatStudios/GazeboMotionCapture#2]
Hi, 

I am simulating a ground robot along with other objects in gazebo. I want to use a motion capture system that provides me with its position and orientation. How can I use this package? I am confused how to use the IP address in this case?

pleas help.

**Comment by Huibean** [comment]
Hi@Angit16 IP address is base base on your gazebo server ip, if it's in same machine is 127.0.0.1,you can use for ground rover, just change your data interface from dronekit to other?
