### ISSUE TITLE
Demo.py runtime issue

### ISSUE THREAD

**Issue by NS100101** [PixelBatStudios/GazeboMotionCapture#3]
Hello,
I am trying to run demo.py in conjunction with PX4 SITL w/ Gazebo. I edited demo.py to reflect the IP address of my machine. 
`GazeboMotionCapture.callback = callback`  
`motion_capture = GazeboMotionCapture.create_motion_capture(('192.168.1.186', 11345))`  
I did also try 127.0.0.1 as well, and ensured the port was correct. However, I get the following runtime error:

> Start simulator (SITL)
Starting copter simulator (SITL)
SITL already Downloaded and Extracted.
Ready to boot.
Connecting to vehicle on: tcp:127.0.0.1:5760
CRITICAL:autopilot:APM:Copter V3.3 (d6053245)
CRITICAL:autopilot:Frame: QUAD
CRITICAL:autopilot:Calibrating barometer
CRITICAL:autopilot:Initialising APM...
CRITICAL:autopilot:barometer calibration complete
CRITICAL:autopilot:GROUND START
(1, (0.10450192945681276, 0.9800527032718428, 0.0), (0.70711233085285752, 0.00074889015951397125, 0.00021415853659370002, 0.70710080247125251))
ERROR:trollius:Exception in callback <lambda>(<Future ...ff\xef?'>) at /usr/local/lib/python2.7/dist-packages/pygazebo-3.0.0_2014.1-py2.7.egg/pygazebo/pygazebo.py:198
handle: <Handle <lambda>(<Future ...ff\xef?'>) at /usr/local/lib/python2.7/dist-packages/pygazebo-3.0.0_2014.1-py2.7.egg/pygazebo/pygazebo.py:198>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/trollius-2.2.post1-py2.7.egg/trollius/events.py", line 136, in _run
    self._callback(*self._args)
  File "/usr/local/lib/python2.7/dist-packages/pygazebo-3.0.0_2014.1-py2.7.egg/pygazebo/pygazebo.py", line 198, in <lambda>
    lambda future: self._handle_read(future, connection))
  File "/usr/local/lib/python2.7/dist-packages/pygazebo-3.0.0_2014.1-py2.7.egg/pygazebo/pygazebo.py", line 209, in _handle_read
    self._connect3(connection)
TypeError: _connect3() takes exactly 3 arguments (2 given)
exiting... motion captrue
Event loop stopped before Future completed.

I've ensured that all dependencies have been installed correctly, and that my PX4 SITL/Gazebo is running properly. Any advice on this would be greatly appreciated. Thank you!

**Comment by Huibean** [comment]
@NS100101 what is your Gazebo version, this repo may out of date

**Comment by NS100101** [comment]
I'm on Gazebo 9. I also believe I just solved the issue. I traced the error back to line 209 in pygazebo.py, and changed the function call `self._connect3(connection)` to `self._connect3(future, connection)` and things seemed to work. Not sure why that `future` got deleted but things are back to normal now. Thank you for your help.
